### ISSUE TITLE
csv files required to have a new line at the end of file

### ISSUE THREAD

**Issue by asalzburger** [msmk0/dfelibs#1]
Hi @msmk0,

looks like when reading back in a `csv` file with a `dfe` reader:

```c++
    using cell_reader = dfe::NamedTupleCsvReader<csv_cell>;

   ...

    cell_collection cells;
    while (creader.read(iocell)){}
```

This requires a new line at the end of the file, otherwise the last line does not return a `true` statement.

Is this intended?

**Comment by msmk0** [comment]
Yes, this is intended. The `csv` readers are intentionally strict about inputs and outputs. Each line **must** be terminated by a newline.
